CREATE TABLE IF NOT EXISTS category(
id SERIAL,
descripcion VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS customer(
id SERIAL,
firstname DATE NOT NULL,
lastname VARCHAR(100) NOT NULL,
nui VARCHAR (100) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
age INT NOT NULL,
PRIMARY KEY (id),
category_id INT NOT NULL,
FOREIGN KEY (category_id) REFERENCES category(id)
);

